#
# python development server (with bpython, tmux, powerline)
#
# build & run cmd:
#       docker build -t dev-server -f Dockerfile-dev-server .
#
#	docker run -ti --privileged --device /dev/fuse:/dev/fuse --volume /Users/pleskac/.ssh/:/home/pleskac/.ssh --name dev-mach-1 --rm dev-server
#	docker exec -ti dev-mach-1 bash
#

FROM python:latest

RUN apt-get -y update
RUN apt-get -y install sudo vim less tmux powerline vim-nox
RUN apt-get -y install kmod sshfs net-tools

# pip
RUN pip install --upgrade pip

# bpython - need to run the latest to fix Save to file Traceback issue
RUN pip install git+https://github.com/bpython/bpython/@master

# user
RUN useradd -ms /bin/bash pleskac
RUN echo 'pleskac:pleskac' | chpasswd
RUN adduser pleskac sudo
USER pleskac
WORKDIR /home/pleskac

# environment
RUN git clone https://github.com/dpleskac/env
RUN ln -s env/.vimrc .vimrc
RUN ln -s env/.tmux.conf .tmux.conf

# powerline (needs vim-nox installed for vim bindings)
RUN echo "" >> ~/.bashrc ; \
    echo "# powerline" >> ~/.bashrc ; \
    echo "if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then source /usr/share/powerline/bindings/bash/powerline.sh; fi" >> ~/.bashrc

# free ctrl-s for bpython
RUN echo "" >> ~/.bashrc ; \
    echo "stty -ixon -ixoff" >> ~/.bashrc ;

RUN echo "" >> ~/.vimrc ; \
    echo "\" powerline" >> ~/.vimrc ; \
    echo "python from powerline.vim import setup as powerline_setup" >> ~/.vimrc ; \
    echo "python powerline_setup()" >> ~/.vimrc ; \
    echo "python del powerline_setup" >> ~/.vimrc ; \
    echo "set laststatus=2" >> ~/.vimrc ;  \
    echo "set showtabline=2" >> ~/.vimrc ; \
    echo "set t_Co=256" >> ~/.vimrc

# git config
RUN git config --global user.email "daniel.pleskac@gmail.com"
RUN git config --global user.name "Daniel Pleskac"
RUN git config --global color.ui true

CMD exec /bin/bash

# mount sshfs
#   sudo chmod o+rw /dev/fuse
#   mkdir ~/secrets
#   sshfs store:groups/infra/secrets/ ~/secrets/
